import Navbar from '@/src/components/Navbar';
import '@/src/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import Provider from '@/src/app/provider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <Provider>
      <body className={inter.className}>
          <Navbar/>
          {children}
        <Toaster/>
      </body>
      </Provider>
    </html>
  );
}
